name = "trmnl"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "TRMNL_WORKERS_KV"
id = "bd9dad65430948879f23dfba951de218"

[ai]
binding = "AI"
remote = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
